

export const PUFF_VALUE = 'PUFF_VALUE';
export const TIMES_PER_DAY_VALUE = 'TIMES_PER_DAY_VALUE';
export const DOSE_ICS_VALUE = 'DOSE_ICS_VALUE';
export const MEDICATION_SELECTION = 'MEDICATION_SELECTION';

export const MEDICATION_TO_STACK = 'MEDICATION_TO_STACK';
export const ON_PUFF_CHANGE = 'ON_PUFF_CHANGE';
export const ON_TIMES_CHANGE = 'ON_TIMES_CHANGE';
export const ON_DOSEICS_CHANGE = 'ON_DOSEICS_CHANGE';
export const ON_MEDICATION_SELECTION = 'ON_MEDICATION_SELECTION';

export const ON_SUBMIT = 'ON_SUBMIT';
export const ON_DELETE_ROW = 'ON_DELETE_ROW';