export const MEDICATION_TO_STACK = 'MEDICATION_TO_STACK';
export const ON_PUFF_CHANGE = 'ON_PUFF_CHANGE';
export const ON_TIMES_CHANGE = 'ON_TIMES_CHANGE';
export const ON_DOSEICS_CHANGE = 'ON_DOSEICS_CHANGE';
export const ON_MEDICATION_SELECTION = 'ON_MEDICATION_SELECTION';

export const ON_SUBMIT = 'ON_SUBMIT';
export const ON_DELETE_ROW = 'ON_DELETE_ROW';
export const FILTERED_MEDICATIONS = 'FILTERED_MEDICATIONS';